; PlatformIO Project Configuration File
;
; Projeto: Cadeira Odontológica com ESP32
; Descrição: Controle via Bluetooth Serial + WiFiManager + Supabase
;

[platformio]
default_envs = esp32s3

[env:esp32dev]
platform = espressif32@6.12.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
upload_port = COM5
monitor_port = COM5
build_flags =
    -D I2C_EARLY_TEST=0
    -D I2C_SDA=21
    -D I2C_SCL=22
    -D I2C_CLOCK_HZ=100000
    -D PCF8574_INT_PIN=1
    -D PIN_RF=23
    -D PIN_SA=36
    -D PORTS_ONLY=0
    -D PORTS_VERIFY=0
    -D PIN_ENCODER1=4
    -D PIN_ENCODER2=35
    -D PIN_ENCODER3=39

; Configurações de memória e partição
board_build.partitions = huge_app.csv

; Bibliotecas necessárias
lib_deps = 
    tzapu/WiFiManager@^2.0.17
    bblanchon/ArduinoJson@^6.21.3
    knolleary/PubSubClient@^2.8

; Configurações do monitor serial
monitor_filters = 
    default
    esp32_exception_decoder

; Porta serial (ajuste conforme necessário)
; upload_port = COM3
; monitor_port = COM3

; Opções de debug
; build_type = debug

[env:esp32s2]
platform = ${env:esp32dev.platform}
board = esp32-s2-saola-1
framework = ${env:esp32dev.framework}
monitor_speed = ${env:esp32dev.monitor_speed}
upload_speed = 460800
upload_port = ${env:esp32dev.upload_port}
monitor_port = ${env:esp32dev.monitor_port}
board_build.partitions = ${env:esp32dev.board_build.partitions}
lib_deps =
    ${env:esp32dev.lib_deps}
monitor_filters =
    ${env:esp32dev.monitor_filters}

[env:esp32s3]
platform = ${env:esp32dev.platform}
board = esp32-s3-devkitc-1
framework = ${env:esp32dev.framework}
monitor_speed = ${env:esp32dev.monitor_speed}
upload_speed = ${env:esp32dev.upload_speed}
upload_port = ${env:esp32dev.upload_port}
monitor_port = ${env:esp32dev.monitor_port}
board_build.partitions = partitions_16MB_ota.csv
board_build.flash_size = 16MB
board_build.psram_type = opi
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB
lib_deps =
    ${env:esp32dev.lib_deps}
monitor_filters =
    ${env:esp32dev.monitor_filters}
build_flags =
    -D I2C_EARLY_TEST=0
    -D I2C_SDA=2
    -D I2C_SCL=18
    -D I2C_CLOCK_HZ=100000
    -D PCF8574_INT_PIN=1
    -D MQTT_MAX_PACKET_SIZE=1024
    -D PIN_RF=15
    -D PIN_SA=14
    -D PIN_GAVETA=20
    -D PIN_TREN_INT_DESCE=3
    -D PIN_INT_TREND_DESCE=8
    -D PORTS_ONLY=0
    -D PORTS_VERIFY=0
    -D TEST_MODE=1
    -D PIN_ENCODER1=4
    -D PIN_ENCODER2=17
    -D PIN_ENCODER3=19
    -D PIN_RELE_SA=16
    -D PIN_RELE_DA=9
    -D PIN_RELE_SE=5
    -D PIN_RELE_DE=6
    -D PIN_RELE_SP=7
    -D PIN_RELE_DP=10
    -D PIN_RELE_REFLETOR=11
    -D PIN_RELE_TREND_DESCE=46
    -D PIN_RELE_TREND_SOBE=47
    -D PIN_LED=12
    -D PIN_BUZZER=13
    -D BOARD_HAS_PSRAM


[env:esp32s3_i2c_17_18]
platform = ${env:esp32s3.platform}
board = ${env:esp32s3.board}
framework = ${env:esp32s3.framework}
monitor_speed = ${env:esp32s3.monitor_speed}
upload_speed = ${env:esp32s3.upload_speed}
upload_port = ${env:esp32s3.upload_port}
monitor_port = ${env:esp32s3.monitor_port}
board_build.partitions = ${env:esp32s3.board_build.partitions}
board_build.flash_size = ${env:esp32s3.board_build.flash_size}
board_build.psram_type = ${env:esp32s3.board_build.psram_type}
board_build.arduino.memory_type = ${env:esp32s3.board_build.arduino.memory_type}
board_upload.flash_size = ${env:esp32s3.board_upload.flash_size}
lib_deps =
    ${env:esp32s3.lib_deps}
monitor_filters =
    ${env:esp32s3.monitor_filters}
build_flags =
    -D I2C_EARLY_TEST=0
    -D I2C_SDA=17
    -D I2C_SCL=18
    -D I2C_CLOCK_HZ=100000
    -D PCF8574_INT_PIN=1
    -D PIN_RF=15
    -D PIN_SA=18
    -D PIN_GAVETA=-1
    -D PORTS_ONLY=0
    -D PORTS_VERIFY=0
    -D PIN_ENCODER1=4
    -D PIN_ENCODER2=17
    -D PIN_ENCODER3=19
    -D PIN_RELE_SA=2
    -D PIN_RELE_DA=3
    -D PIN_RELE_SE=5
    -D PIN_RELE_DE=6
    -D PIN_RELE_SP=7
    -D PIN_RELE_DP=10
    -D PIN_RELE_REFLETOR=11
    -D PIN_LED=12
    -D PIN_BUZZER=13
    -D BOARD_HAS_PSRAM

[env:esp32s3_i2c_21_22]
platform = ${env:esp32s3.platform}
board = ${env:esp32s3.board}
framework = ${env:esp32s3.framework}
monitor_speed = ${env:esp32s3.monitor_speed}
upload_speed = ${env:esp32s3.upload_speed}
upload_port = ${env:esp32s3.upload_port}
monitor_port = ${env:esp32s3.monitor_port}
board_build.partitions = ${env:esp32s3.board_build.partitions}
board_build.flash_size = ${env:esp32s3.board_build.flash_size}
board_build.psram_type = ${env:esp32s3.board_build.psram_type}
board_build.arduino.memory_type = ${env:esp32s3.board_build.arduino.memory_type}
board_upload.flash_size = ${env:esp32s3.board_upload.flash_size}
lib_deps =
    ${env:esp32s3.lib_deps}
monitor_filters =
    ${env:esp32s3.monitor_filters}
build_flags =
    -D I2C_EARLY_TEST=0
    -D I2C_SDA=21
    -D I2C_SCL=22
    -D I2C_CLOCK_HZ=100000
    -D PCF8574_INT_PIN=1
    -D PIN_RF=15
    -D PIN_SA=18
    -D PIN_GAVETA=-1
    -D PORTS_ONLY=0
    -D PORTS_VERIFY=0
    -D PIN_ENCODER1=4
    -D PIN_ENCODER2=17
    -D PIN_ENCODER3=19
    -D PIN_RELE_SA=2
    -D PIN_RELE_DA=3
    -D PIN_RELE_SE=5
    -D PIN_RELE_DE=6
    -D PIN_RELE_SP=7
    -D PIN_RELE_DP=10
    -D PIN_RELE_REFLETOR=11
    -D PIN_LED=12
    -D PIN_BUZZER=13
    -D BOARD_HAS_PSRAM

[env:esp32s3_i2c_21_20]
platform = ${env:esp32s3.platform}
board = ${env:esp32s3.board}
framework = ${env:esp32s3.framework}
monitor_speed = ${env:esp32s3.monitor_speed}
upload_speed = ${env:esp32s3.upload_speed}
upload_port = ${env:esp32s3.upload_port}
monitor_port = ${env:esp32s3.monitor_port}
board_build.partitions = ${env:esp32s3.board_build.partitions}
board_build.flash_size = ${env:esp32s3.board_build.flash_size}
board_build.psram_type = ${env:esp32s3.board_build.psram_type}
board_build.arduino.memory_type = ${env:esp32s3.board_build.arduino.memory_type}
board_upload.flash_size = ${env:esp32s3.board_upload.flash_size}
lib_deps =
    ${env:esp32s3.lib_deps}
monitor_filters =
    ${env:esp32s3.monitor_filters}
build_flags =
    -D I2C_EARLY_TEST=0
    -D I2C_SDA=21
    -D I2C_SCL=20
    -D I2C_CLOCK_HZ=100000
    -D PCF8574_INT_PIN=1
    -D PIN_RF=15
    -D PIN_SA=18
    -D PIN_GAVETA=-1
    -D PORTS_ONLY=0
    -D PORTS_VERIFY=0
    -D PIN_ENCODER1=4
    -D PIN_ENCODER2=17
    -D PIN_ENCODER3=19
    -D PIN_RELE_SA=2
    -D PIN_RELE_DA=3
    -D PIN_RELE_SE=5
    -D PIN_RELE_DE=6
    -D PIN_RELE_SP=7
    -D PIN_RELE_DP=10
    -D PIN_RELE_REFLETOR=11
    -D PIN_LED=12
    -D PIN_BUZZER=13
    -D BOARD_HAS_PSRAM

[env:esp32s3_i2c_21_18]
platform = ${env:esp32s3.platform}
board = ${env:esp32s3.board}
framework = ${env:esp32s3.framework}
monitor_speed = ${env:esp32s3.monitor_speed}
upload_speed = ${env:esp32s3.upload_speed}
upload_port = ${env:esp32s3.upload_port}
monitor_port = ${env:esp32s3.monitor_port}
board_build.partitions = ${env:esp32s3.board_build.partitions}
board_build.flash_size = ${env:esp32s3.board_build.flash_size}
board_build.psram_type = ${env:esp32s3.board_build.psram_type}
board_build.arduino.memory_type = ${env:esp32s3.board_build.arduino.memory_type}
board_upload.flash_size = ${env:esp32s3.board_upload.flash_size}
lib_deps =
    ${env:esp32s3.lib_deps}
monitor_filters =
    ${env:esp32s3.monitor_filters}
build_flags =
    -D I2C_EARLY_TEST=0
    -D I2C_SDA=0
    -D I2C_SCL=18
    -D I2C_CLOCK_HZ=10000
    -D PCF8574_INT_PIN=1
    -D PIN_RF=15
    -D PIN_SA=14
    -D PIN_GAVETA=20
    -D PORTS_ONLY=0
    -D PORTS_VERIFY=0
    -D PIN_ENCODER1=4
    -D PIN_ENCODER2=17
    -D PIN_ENCODER3=19
    -D PIN_RELE_SA=2
    -D PIN_RELE_DA=3
    -D PIN_RELE_SE=5
    -D PIN_RELE_DE=6
    -D PIN_RELE_SP=7
    -D PIN_RELE_DP=10
    -D PIN_RELE_REFLETOR=11
    -D PIN_LED=12
    -D PIN_BUZZER=13
    -D BOARD_HAS_PSRAM

[env:esp32s3_i2c_1_18]
platform = ${env:esp32s3.platform}
board = ${env:esp32s3.board}
framework = ${env:esp32s3.framework}
monitor_speed = ${env:esp32s3.monitor_speed}
upload_speed = ${env:esp32s3.upload_speed}
upload_port = ${env:esp32s3.upload_port}
monitor_port = ${env:esp32s3.monitor_port}
board_build.partitions = ${env:esp32s3.board_build.partitions}
board_build.flash_size = ${env:esp32s3.board_build.flash_size}
board_build.psram_type = ${env:esp32s3.board_build.psram_type}
board_build.arduino.memory_type = ${env:esp32s3.board_build.arduino.memory_type}
board_upload.flash_size = ${env:esp32s3.board_upload.flash_size}
lib_deps =
    ${env:esp32s3.lib_deps}
monitor_filters =
    ${env:esp32s3.monitor_filters}
build_flags =
    -D I2C_EARLY_TEST=0
    -D I2C_SDA=1
    -D I2C_SCL=18
    -D I2C_CLOCK_HZ=10000
    -D PCF8574_INT_PIN=1
    -D PIN_RF=15
    -D PIN_SA=14
    -D PIN_GAVETA=20
    -D PORTS_ONLY=0
    -D PORTS_VERIFY=0
    -D PIN_ENCODER1=4
    -D PIN_ENCODER2=17
    -D PIN_ENCODER3=19
    -D PIN_RELE_SA=2
    -D PIN_RELE_DA=3
    -D PIN_RELE_SE=5
    -D PIN_RELE_DE=6
    -D PIN_RELE_SP=7
    -D PIN_RELE_DP=10
    -D PIN_RELE_REFLETOR=11
    -D PIN_LED=12
    -D PIN_BUZZER=13
    -D BOARD_HAS_PSRAM

[env:esp32s3_i2c_2_18]
platform = ${env:esp32s3.platform}
board = ${env:esp32s3.board}
framework = ${env:esp32s3.framework}
monitor_speed = ${env:esp32s3.monitor_speed}
upload_speed = ${env:esp32s3.upload_speed}
upload_port = ${env:esp32s3.upload_port}
monitor_port = ${env:esp32s3.monitor_port}
board_build.partitions = ${env:esp32s3.board_build.partitions}
board_build.flash_size = ${env:esp32s3.board_build.flash_size}
board_build.psram_type = ${env:esp32s3.board_build.psram_type}
board_build.arduino.memory_type = ${env:esp32s3.board_build.arduino.memory_type}
board_upload.flash_size = ${env:esp32s3.board_upload.flash_size}
lib_deps =
    ${env:esp32s3.lib_deps}
monitor_filters =
    ${env:esp32s3.monitor_filters}
build_flags =
    -D I2C_EARLY_TEST=0
    -D I2C_SDA=2
    -D I2C_SCL=18
    -D I2C_CLOCK_HZ=100000
    -D PCF8574_INT_PIN=1
    -D PIN_RF=15
    -D PIN_SA=14
    -D PIN_GAVETA=20
    -D PORTS_ONLY=0
    -D PORTS_VERIFY=0
    -D PIN_ENCODER1=4
    -D PIN_ENCODER2=17
    -D PIN_ENCODER3=19
    -D PIN_RELE_SA=16
    -D PIN_RELE_DA=9
    -D PIN_RELE_SE=5
    -D PIN_RELE_DE=6
    -D PIN_RELE_SP=7
    -D PIN_RELE_DP=10
    -D PIN_RELE_REFLETOR=11
    -D PIN_LED=12
    -D PIN_BUZZER=13
    -D BOARD_HAS_PSRAM

[env:esp32s3_i2c_3_18]
platform = ${env:esp32s3.platform}
board = ${env:esp32s3.board}
framework = ${env:esp32s3.framework}
monitor_speed = ${env:esp32s3.monitor_speed}
upload_speed = ${env:esp32s3.upload_speed}
upload_port = ${env:esp32s3.upload_port}
monitor_port = ${env:esp32s3.monitor_port}
board_build.partitions = ${env:esp32s3.board_build.partitions}
board_build.flash_size = ${env:esp32s3.board_build.flash_size}
board_build.psram_type = ${env:esp32s3.board_build.psram_type}
board_build.arduino.memory_type = ${env:esp32s3.board_build.arduino.memory_type}
board_upload.flash_size = ${env:esp32s3.board_upload.flash_size}
lib_deps =
    ${env:esp32s3.lib_deps}
monitor_filters =
    ${env:esp32s3.monitor_filters}
build_flags =
    -D I2C_EARLY_TEST=0
    -D I2C_SDA=3
    -D I2C_SCL=18
    -D I2C_CLOCK_HZ=10000
    -D PCF8574_INT_PIN=1
    -D PIN_RF=15
    -D PIN_SA=14
    -D PIN_GAVETA=-1
    -D PORTS_ONLY=0
    -D PORTS_VERIFY=0
    -D PIN_ENCODER1=4
    -D PIN_ENCODER2=17
    -D PIN_ENCODER3=19
    -D PIN_RELE_SA=2
    -D PIN_RELE_DA=21
    -D PIN_RELE_SE=5
    -D PIN_RELE_DE=6
    -D PIN_RELE_SP=7
    -D PIN_RELE_DP=10
    -D PIN_RELE_REFLETOR=11
    -D PIN_LED=12
    -D PIN_BUZZER=13
    -D BOARD_HAS_PSRAM
